CREATE TABLE scopes
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_scopes PRIMARY KEY (id)
);

CREATE TABLE temperature_data
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    thermostat_id BIGINT,
    temperature   DECIMAL                                 NOT NULL,
    timestamp     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_temperature_data PRIMARY KEY (id)
);

CREATE TABLE thermostat_alerts
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    thermostat_id BIGINT,
    message       VARCHAR(255)                            NOT NULL,
    resolved      BOOLEAN                                 NOT NULL,
    resolved_at   TIMESTAMP WITHOUT TIME ZONE,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_thermostat_alerts PRIMARY KEY (id)
);

CREATE TABLE thermostats
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                BIGINT,
    name                   VARCHAR(255)                            NOT NULL,
    location               VARCHAR(255)                            NOT NULL,
    threshold_temperature  DECIMAL,
    configured_temperature DECIMAL                                 NOT NULL,
    is_critical            BOOLEAN                                 NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_thermostats PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(64)                             NOT NULL,
    name       VARCHAR(64)                             NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_scopes
(
    scope_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE temperature_data
    ADD CONSTRAINT FK_TEMPERATURE_DATA_ON_THERMOSTAT FOREIGN KEY (thermostat_id) REFERENCES thermostats (id);

ALTER TABLE thermostats
    ADD CONSTRAINT FK_THERMOSTATS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE thermostat_alerts
    ADD CONSTRAINT FK_THERMOSTAT_ALERTS_ON_THERMOSTAT FOREIGN KEY (thermostat_id) REFERENCES thermostats (id);

ALTER TABLE users_scopes
    ADD CONSTRAINT fk_userol_on_scope_entity FOREIGN KEY (scope_id) REFERENCES scopes (id);

ALTER TABLE users_scopes
    ADD CONSTRAINT fk_userol_on_user_entity FOREIGN KEY (user_id) REFERENCES users (id);